apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
  labels:
    app: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      containers:
        - name: web-deployment
          image: "{IMAGE}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: web-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
